/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        lavender: {
          50: "hsl(var(--color-lavender-50))",
          100: "hsl(var(--color-lavender-100))",
          200: "hsl(var(--color-lavender-200))",
          300: "hsl(var(--color-lavender-300))",
          400: "hsl(var(--color-lavender-400))",
          500: "hsl(var(--color-lavender-500))",
          600: "hsl(var(--color-lavender-600))",
          700: "hsl(var(--color-lavender-700))",
          800: "hsl(var(--color-lavender-800))",
          900: "hsl(var(--color-lavender-900))",
          950: "hsl(var(--color-lavender-950))",
        },
        "lavender-grey": {
          50: "hsl(var(--color-lavender-grey-50))",
          100: "hsl(var(--color-lavender-grey-100))",
          200: "hsl(var(--color-lavender-grey-200))",
          300: "hsl(var(--color-lavender-grey-300))",
          400: "hsl(var(--color-lavender-grey-400))",
          500: "hsl(var(--color-lavender-grey-500))",
          600: "hsl(var(--color-lavender-grey-600))",
          700: "hsl(var(--color-lavender-grey-700))",
          800: "hsl(var(--color-lavender-grey-800))",
          900: "hsl(var(--color-lavender-grey-900))",
          950: "hsl(var(--color-lavender-grey-950))",
        },
        "powder-blue": {
          50: "hsl(var(--color-powder-blue-50))",
          100: "hsl(var(--color-powder-blue-100))",
          200: "hsl(var(--color-powder-blue-200))",
          300: "hsl(var(--color-powder-blue-300))",
          400: "hsl(var(--color-powder-blue-400))",
          500: "hsl(var(--color-powder-blue-500))",
          600: "hsl(var(--color-powder-blue-600))",
          700: "hsl(var(--color-powder-blue-700))",
          800: "hsl(var(--color-powder-blue-800))",
          900: "hsl(var(--color-powder-blue-900))",
          950: "hsl(var(--color-powder-blue-950))",
        },
        "baltic-blue": {
          50: "hsl(var(--color-baltic-blue-50))",
          100: "hsl(var(--color-baltic-blue-100))",
          200: "hsl(var(--color-baltic-blue-200))",
          300: "hsl(var(--color-baltic-blue-300))",
          400: "hsl(var(--color-baltic-blue-400))",
          500: "hsl(var(--color-baltic-blue-500))",
          600: "hsl(var(--color-baltic-blue-600))",
          700: "hsl(var(--color-baltic-blue-700))",
          800: "hsl(var(--color-baltic-blue-800))",
          900: "hsl(var(--color-baltic-blue-900))",
          950: "hsl(var(--color-baltic-blue-950))",
        },
        "muted-teal": {
          50: "hsl(var(--color-muted-teal-50))",
          100: "hsl(var(--color-muted-teal-100))",
          200: "hsl(var(--color-muted-teal-200))",
          300: "hsl(var(--color-muted-teal-300))",
          400: "hsl(var(--color-muted-teal-400))",
          500: "hsl(var(--color-muted-teal-500))",
          600: "hsl(var(--color-muted-teal-600))",
          700: "hsl(var(--color-muted-teal-700))",
          800: "hsl(var(--color-muted-teal-800))",
          900: "hsl(var(--color-muted-teal-900))",
          950: "hsl(var(--color-muted-teal-950))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};
